[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.virtualenv', 'gcc', 'postgresql']

[phases.install]
cmds = ['pip3 install --no-cache-dir -r requirements.txt']

[start]
cmd = 'python3 -m app.main'
